

### my router
GET  http://localhost:3000/message


## to send my message

POST http://localhost:3000/message

content-type: application/json
{
"content":"hi there testing here now my content"
}

## to get my message by id
GET  http://localhost:3000/message/432434234
